spring.application.name=UserService

spring.datasource.name=UserService
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.url=jdbc:postgresql://localhost:5432/UserService
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate dialect (must be separate)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway migrations
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration



# keep validate in prod; for dev you can use "update"
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true

eureka.instance.prefer-ip-address: true
