spring:
  application:
    name: BookingService
  datasource:
    name: booking_service
    username: postgres
    password: Nik@9905366469
    url: jdbc:postgresql://localhost:5432/booking_service
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

razorpay:
  api:
    key: rzp_test_SfQqx5y2AUfBbB
    secret: KG8oWAS129JIqs0bt8LjIHGu


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8096